server:
  port: 8080

vaadin:
  launch-browser: true

spring:
  application:
    name: parser-html-game
  profiles:
    active: production


management:
  endpoints:
    web:
      exposure:
        include: health,info,env,caches
